[workspace]
members = ["crates/wasm", "crates/codegen-tritonvm", "crates/ir", "crates/frontend", "crates/codegen", "crates/codegen-shared", "crates/compiler"]
exclude = []
resolver = "2"

[workspace.package]
authors = [
    "Denys Zadorozhny <denys@zadorozhnyi.com>"
]
repository = "https://github.com/greenhat/c2zk"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
keywords = ["wasm", "webassembly", "zk", "proof", "verification"]
categories = ["wasm", "no-std", "virtualization"]

[workspace.dependencies]
c2zk-ir = { path = "crates/ir" }
c2zk-frontend = { path = "crates/frontend" }
c2zk-codegen = { path = "crates/codegen" }
c2zk-codegen-shared = { path = "crates/codegen-shared" }
c2zk-codegen-tritonvm = { path = "crates/codegen-tritonvm" }
wasmparser = { version = "0.94", features = ["deterministic"] }
log = { version = "0.4.8", default-features = false }
smallvec = { version = "1.6.1", features = ["union"] }
wat = "1.0.49"
target-lexicon = { version = "0.12.3", default-features = false }
derive_more = "0.99"
thiserror = "1.0"
