[workspace]
members = ["crates/wasm2zk-tritonvm", "crates/wasm2zk-wasmparser"]
exclude = []
resolver = "2"

[workspace.package]
authors = [
    "Denys Zadorozhny <denys@zadorozhnyi.com>"
]
repository = "https://github.com/greenhat/wasm2zk"
edition = "2021"
readme = "README.md"
license = "Apache-2.0"
keywords = ["wasm", "webassembly", "zk", "proof", "verification"]
categories = ["wasm", "no-std", "virtualization"]
