[package]
name = "c2zk-codegen-tritonvm"
version = "0.1.0"
description = "Triton VM backend for c2zk"
authors.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
c2zk-ir = { workspace = true }
c2zk-codegen-shared = { workspace = true }
triton-vm = { path = "../../../triton-vm/triton-vm" }
twenty-first = { version = "0.3.2" }

[dev-dependencies]
